baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "bichanna's blog"
theme = 'PaperMod'

[params]
defaultTheme = "auto"

[params.homeInfoParams]
Title = "Hi there, I'm Nobuharu Shimazu 👋"
Content = "I'm a 16-year-old Japanese student living in Evanston, IL (moving to Toronto in a month)."

[[params.socialIcons]]
name = "github"
url = "https://github.com/bichanna"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/nobuharushimazu"
